services:
  db:
    image: postgres:16
    container_name: cars-db
    environment:
      POSTGRES_USER: cars
      POSTGRES_PASSWORD: cars
      POSTGRES_DB: cars
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cars -d cars"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data

  jaeger:
    image: jaegertracing/all-in-one:1.57
    container_name: jaeger
    ports:
      - "16686:16686"   
      - "4318:4318"     
    environment:
      COLLECTOR_OTLP_ENABLED: "true"

volumes:
  pg_data: