version: '3.9'

services:
  db:
    image: postgres:16
    container_name: cars-db
    restart: always
    environment:
      POSTGRES_USER: cars
      POSTGRES_PASSWORD: cars
      POSTGRES_DB: cars
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cars -d cars"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pg_data: