name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-release:
    name: Build & Publish
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
          cache: true

      - name: Build binary
        run: |
          go build -o bin/service-cars ./cmd

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: service-cars-bin
          path: bin/service-cars

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true

      # GHCR (GitHub Container Registry)
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push image to GHCR
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/service-cars:${{ github.ref_name }}
