name: Tests

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  tests:
    name: Run tests (Go 1.22.x)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Download deps
        run: go mod download
      - name: Run tests
        run: go test -race -cover ./...